// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.spaceuptech.clientapi;

public final class Schema {
    private Schema() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:schema.Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required .schema.Message.Type type = 1;</code>
         */
        boolean hasType();
        /**
         * <code>required .schema.Message.Type type = 1;</code>
         */
        com.spaceuptech.clientapi.Schema.Message.Type getType();

        /**
         * <code>optional bytes data = 2;</code>
         */
        boolean hasData();
        /**
         * <code>optional bytes data = 2;</code>
         */
        com.google.protobuf.ByteString getData();

        /**
         * <code>optional .schema.Faas faas = 3;</code>
         */
        boolean hasFaas();
        /**
         * <code>optional .schema.Faas faas = 3;</code>
         */
        com.spaceuptech.clientapi.Schema.Faas getFaas();
        /**
         * <code>optional .schema.Faas faas = 3;</code>
         */
        com.spaceuptech.clientapi.Schema.FaasOrBuilder getFaasOrBuilder();
    }
    /**
     * Protobuf type {@code schema.Message}
     */
    public  static final class Message extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:schema.Message)
            MessageOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Message() {
            type_ = 0;
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            com.spaceuptech.clientapi.Schema.Message.Type value = com.spaceuptech.clientapi.Schema.Message.Type.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(1, rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                type_ = rawValue;
                            }
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            data_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            com.spaceuptech.clientapi.Schema.Faas.Builder subBuilder = null;
                            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                                subBuilder = faas_.toBuilder();
                            }
                            faas_ = input.readMessage(com.spaceuptech.clientapi.Schema.Faas.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(faas_);
                                faas_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000004;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.spaceuptech.clientapi.Schema.internal_static_schema_Message_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.spaceuptech.clientapi.Schema.internal_static_schema_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.spaceuptech.clientapi.Schema.Message.class, com.spaceuptech.clientapi.Schema.Message.Builder.class);
        }

        /**
         * Protobuf enum {@code schema.Message.Type}
         */
        public enum Type
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>PING = 0;</code>
             */
            PING(0),
            /**
             * <code>PONG = 1;</code>
             */
            PONG(1),
            /**
             * <code>PROXY = 2;</code>
             */
            PROXY(2),
            /**
             * <code>FAAS = 3;</code>
             */
            FAAS(3),
            ;

            /**
             * <code>PING = 0;</code>
             */
            public static final int PING_VALUE = 0;
            /**
             * <code>PONG = 1;</code>
             */
            public static final int PONG_VALUE = 1;
            /**
             * <code>PROXY = 2;</code>
             */
            public static final int PROXY_VALUE = 2;
            /**
             * <code>FAAS = 3;</code>
             */
            public static final int FAAS_VALUE = 3;


            public final int getNumber() {
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Type valueOf(int value) {
                return forNumber(value);
            }

            public static Type forNumber(int value) {
                switch (value) {
                    case 0: return PING;
                    case 1: return PONG;
                    case 2: return PROXY;
                    case 3: return FAAS;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Type> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                        public Type findValueByNumber(int number) {
                            return Type.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }
            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return com.spaceuptech.clientapi.Schema.Message.getDescriptor().getEnumTypes().get(0);
            }

            private static final Type[] VALUES = values();

            public static Type valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private Type(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:schema.Message.Type)
        }

        private int bitField0_;
        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;
        /**
         * <code>required .schema.Message.Type type = 1;</code>
         */
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .schema.Message.Type type = 1;</code>
         */
        public com.spaceuptech.clientapi.Schema.Message.Type getType() {
            com.spaceuptech.clientapi.Schema.Message.Type result = com.spaceuptech.clientapi.Schema.Message.Type.valueOf(type_);
            return result == null ? com.spaceuptech.clientapi.Schema.Message.Type.PING : result;
        }

        public static final int DATA_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString data_;
        /**
         * <code>optional bytes data = 2;</code>
         */
        public boolean hasData() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional bytes data = 2;</code>
         */
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        public static final int FAAS_FIELD_NUMBER = 3;
        private com.spaceuptech.clientapi.Schema.Faas faas_;
        /**
         * <code>optional .schema.Faas faas = 3;</code>
         */
        public boolean hasFaas() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional .schema.Faas faas = 3;</code>
         */
        public com.spaceuptech.clientapi.Schema.Faas getFaas() {
            return faas_ == null ? com.spaceuptech.clientapi.Schema.Faas.getDefaultInstance() : faas_;
        }
        /**
         * <code>optional .schema.Faas faas = 3;</code>
         */
        public com.spaceuptech.clientapi.Schema.FaasOrBuilder getFaasOrBuilder() {
            return faas_ == null ? com.spaceuptech.clientapi.Schema.Faas.getDefaultInstance() : faas_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (hasFaas()) {
                if (!getFaas().isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, type_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, data_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeMessage(3, getFaas());
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, type_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, data_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getFaas());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.spaceuptech.clientapi.Schema.Message)) {
                return super.equals(obj);
            }
            com.spaceuptech.clientapi.Schema.Message other = (com.spaceuptech.clientapi.Schema.Message) obj;

            boolean result = true;
            result = result && (hasType() == other.hasType());
            if (hasType()) {
                result = result && type_ == other.type_;
            }
            result = result && (hasData() == other.hasData());
            if (hasData()) {
                result = result && getData()
                        .equals(other.getData());
            }
            result = result && (hasFaas() == other.hasFaas());
            if (hasFaas()) {
                result = result && getFaas()
                        .equals(other.getFaas());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasType()) {
                hash = (37 * hash) + TYPE_FIELD_NUMBER;
                hash = (53 * hash) + type_;
            }
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            if (hasFaas()) {
                hash = (37 * hash) + FAAS_FIELD_NUMBER;
                hash = (53 * hash) + getFaas().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.spaceuptech.clientapi.Schema.Message parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.spaceuptech.clientapi.Schema.Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.spaceuptech.clientapi.Schema.Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code schema.Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:schema.Message)
                com.spaceuptech.clientapi.Schema.MessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.spaceuptech.clientapi.Schema.internal_static_schema_Message_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.spaceuptech.clientapi.Schema.internal_static_schema_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.spaceuptech.clientapi.Schema.Message.class, com.spaceuptech.clientapi.Schema.Message.Builder.class);
            }

            // Construct using com.spaceuptech.clientapi.Schema.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getFaasFieldBuilder();
                }
            }
            public Builder clear() {
                super.clear();
                type_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                data_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                if (faasBuilder_ == null) {
                    faas_ = null;
                } else {
                    faasBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.spaceuptech.clientapi.Schema.internal_static_schema_Message_descriptor;
            }

            public com.spaceuptech.clientapi.Schema.Message getDefaultInstanceForType() {
                return com.spaceuptech.clientapi.Schema.Message.getDefaultInstance();
            }

            public com.spaceuptech.clientapi.Schema.Message build() {
                com.spaceuptech.clientapi.Schema.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.spaceuptech.clientapi.Schema.Message buildPartial() {
                com.spaceuptech.clientapi.Schema.Message result = new com.spaceuptech.clientapi.Schema.Message(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.type_ = type_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.data_ = data_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                if (faasBuilder_ == null) {
                    result.faas_ = faas_;
                } else {
                    result.faas_ = faasBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.spaceuptech.clientapi.Schema.Message) {
                    return mergeFrom((com.spaceuptech.clientapi.Schema.Message)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.spaceuptech.clientapi.Schema.Message other) {
                if (other == com.spaceuptech.clientapi.Schema.Message.getDefaultInstance()) return this;
                if (other.hasType()) {
                    setType(other.getType());
                }
                if (other.hasData()) {
                    setData(other.getData());
                }
                if (other.hasFaas()) {
                    mergeFaas(other.getFaas());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasType()) {
                    return false;
                }
                if (hasFaas()) {
                    if (!getFaas().isInitialized()) {
                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.spaceuptech.clientapi.Schema.Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.spaceuptech.clientapi.Schema.Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int type_ = 0;
            /**
             * <code>required .schema.Message.Type type = 1;</code>
             */
            public boolean hasType() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required .schema.Message.Type type = 1;</code>
             */
            public com.spaceuptech.clientapi.Schema.Message.Type getType() {
                com.spaceuptech.clientapi.Schema.Message.Type result = com.spaceuptech.clientapi.Schema.Message.Type.valueOf(type_);
                return result == null ? com.spaceuptech.clientapi.Schema.Message.Type.PING : result;
            }
            /**
             * <code>required .schema.Message.Type type = 1;</code>
             */
            public Builder setType(com.spaceuptech.clientapi.Schema.Message.Type value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                type_ = value.getNumber();
                onChanged();
                return this;
            }
            /**
             * <code>required .schema.Message.Type type = 1;</code>
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>optional bytes data = 2;</code>
             */
            public boolean hasData() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>optional bytes data = 2;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }
            /**
             * <code>optional bytes data = 2;</code>
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                data_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional bytes data = 2;</code>
             */
            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000002);
                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            private com.spaceuptech.clientapi.Schema.Faas faas_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.spaceuptech.clientapi.Schema.Faas, com.spaceuptech.clientapi.Schema.Faas.Builder, com.spaceuptech.clientapi.Schema.FaasOrBuilder> faasBuilder_;
            /**
             * <code>optional .schema.Faas faas = 3;</code>
             */
            public boolean hasFaas() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>optional .schema.Faas faas = 3;</code>
             */
            public com.spaceuptech.clientapi.Schema.Faas getFaas() {
                if (faasBuilder_ == null) {
                    return faas_ == null ? com.spaceuptech.clientapi.Schema.Faas.getDefaultInstance() : faas_;
                } else {
                    return faasBuilder_.getMessage();
                }
            }
            /**
             * <code>optional .schema.Faas faas = 3;</code>
             */
            public Builder setFaas(com.spaceuptech.clientapi.Schema.Faas value) {
                if (faasBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    faas_ = value;
                    onChanged();
                } else {
                    faasBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000004;
                return this;
            }
            /**
             * <code>optional .schema.Faas faas = 3;</code>
             */
            public Builder setFaas(
                    com.spaceuptech.clientapi.Schema.Faas.Builder builderForValue) {
                if (faasBuilder_ == null) {
                    faas_ = builderForValue.build();
                    onChanged();
                } else {
                    faasBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000004;
                return this;
            }
            /**
             * <code>optional .schema.Faas faas = 3;</code>
             */
            public Builder mergeFaas(com.spaceuptech.clientapi.Schema.Faas value) {
                if (faasBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004) &&
                            faas_ != null &&
                            faas_ != com.spaceuptech.clientapi.Schema.Faas.getDefaultInstance()) {
                        faas_ =
                                com.spaceuptech.clientapi.Schema.Faas.newBuilder(faas_).mergeFrom(value).buildPartial();
                    } else {
                        faas_ = value;
                    }
                    onChanged();
                } else {
                    faasBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000004;
                return this;
            }
            /**
             * <code>optional .schema.Faas faas = 3;</code>
             */
            public Builder clearFaas() {
                if (faasBuilder_ == null) {
                    faas_ = null;
                    onChanged();
                } else {
                    faasBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }
            /**
             * <code>optional .schema.Faas faas = 3;</code>
             */
            public com.spaceuptech.clientapi.Schema.Faas.Builder getFaasBuilder() {
                bitField0_ |= 0x00000004;
                onChanged();
                return getFaasFieldBuilder().getBuilder();
            }
            /**
             * <code>optional .schema.Faas faas = 3;</code>
             */
            public com.spaceuptech.clientapi.Schema.FaasOrBuilder getFaasOrBuilder() {
                if (faasBuilder_ != null) {
                    return faasBuilder_.getMessageOrBuilder();
                } else {
                    return faas_ == null ?
                            com.spaceuptech.clientapi.Schema.Faas.getDefaultInstance() : faas_;
                }
            }
            /**
             * <code>optional .schema.Faas faas = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.spaceuptech.clientapi.Schema.Faas, com.spaceuptech.clientapi.Schema.Faas.Builder, com.spaceuptech.clientapi.Schema.FaasOrBuilder>
            getFaasFieldBuilder() {
                if (faasBuilder_ == null) {
                    faasBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.spaceuptech.clientapi.Schema.Faas, com.spaceuptech.clientapi.Schema.Faas.Builder, com.spaceuptech.clientapi.Schema.FaasOrBuilder>(
                            getFaas(),
                            getParentForChildren(),
                            isClean());
                    faas_ = null;
                }
                return faasBuilder_;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:schema.Message)
        }

        // @@protoc_insertion_point(class_scope:schema.Message)
        private static final com.spaceuptech.clientapi.Schema.Message DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.spaceuptech.clientapi.Schema.Message();
        }

        public static com.spaceuptech.clientapi.Schema.Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
                PARSER = new com.google.protobuf.AbstractParser<Message>() {
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        public com.spaceuptech.clientapi.Schema.Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface FaasOrBuilder extends
            // @@protoc_insertion_point(interface_extends:schema.Faas)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string engine = 1;</code>
         */
        boolean hasEngine();
        /**
         * <code>required string engine = 1;</code>
         */
        java.lang.String getEngine();
        /**
         * <code>required string engine = 1;</code>
         */
        com.google.protobuf.ByteString
        getEngineBytes();

        /**
         * <code>required string func = 2;</code>
         */
        boolean hasFunc();
        /**
         * <code>required string func = 2;</code>
         */
        java.lang.String getFunc();
        /**
         * <code>required string func = 2;</code>
         */
        com.google.protobuf.ByteString
        getFuncBytes();

        /**
         * <code>optional bytes args = 3;</code>
         */
        boolean hasArgs();
        /**
         * <code>optional bytes args = 3;</code>
         */
        com.google.protobuf.ByteString getArgs();
    }
    /**
     * Protobuf type {@code schema.Faas}
     */
    public  static final class Faas extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:schema.Faas)
            FaasOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Faas.newBuilder() to construct.
        private Faas(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Faas() {
            engine_ = "";
            func_ = "";
            args_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Faas(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            engine_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            func_ = bs;
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            args_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.spaceuptech.clientapi.Schema.internal_static_schema_Faas_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.spaceuptech.clientapi.Schema.internal_static_schema_Faas_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.spaceuptech.clientapi.Schema.Faas.class, com.spaceuptech.clientapi.Schema.Faas.Builder.class);
        }

        private int bitField0_;
        public static final int ENGINE_FIELD_NUMBER = 1;
        private volatile java.lang.Object engine_;
        /**
         * <code>required string engine = 1;</code>
         */
        public boolean hasEngine() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string engine = 1;</code>
         */
        public java.lang.String getEngine() {
            java.lang.Object ref = engine_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    engine_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string engine = 1;</code>
         */
        public com.google.protobuf.ByteString
        getEngineBytes() {
            java.lang.Object ref = engine_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                engine_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FUNC_FIELD_NUMBER = 2;
        private volatile java.lang.Object func_;
        /**
         * <code>required string func = 2;</code>
         */
        public boolean hasFunc() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string func = 2;</code>
         */
        public java.lang.String getFunc() {
            java.lang.Object ref = func_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    func_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string func = 2;</code>
         */
        public com.google.protobuf.ByteString
        getFuncBytes() {
            java.lang.Object ref = func_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                func_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ARGS_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString args_;
        /**
         * <code>optional bytes args = 3;</code>
         */
        public boolean hasArgs() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional bytes args = 3;</code>
         */
        public com.google.protobuf.ByteString getArgs() {
            return args_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasEngine()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasFunc()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, engine_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, func_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, args_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, engine_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, func_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, args_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.spaceuptech.clientapi.Schema.Faas)) {
                return super.equals(obj);
            }
            com.spaceuptech.clientapi.Schema.Faas other = (com.spaceuptech.clientapi.Schema.Faas) obj;

            boolean result = true;
            result = result && (hasEngine() == other.hasEngine());
            if (hasEngine()) {
                result = result && getEngine()
                        .equals(other.getEngine());
            }
            result = result && (hasFunc() == other.hasFunc());
            if (hasFunc()) {
                result = result && getFunc()
                        .equals(other.getFunc());
            }
            result = result && (hasArgs() == other.hasArgs());
            if (hasArgs()) {
                result = result && getArgs()
                        .equals(other.getArgs());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasEngine()) {
                hash = (37 * hash) + ENGINE_FIELD_NUMBER;
                hash = (53 * hash) + getEngine().hashCode();
            }
            if (hasFunc()) {
                hash = (37 * hash) + FUNC_FIELD_NUMBER;
                hash = (53 * hash) + getFunc().hashCode();
            }
            if (hasArgs()) {
                hash = (37 * hash) + ARGS_FIELD_NUMBER;
                hash = (53 * hash) + getArgs().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.spaceuptech.clientapi.Schema.Faas parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.spaceuptech.clientapi.Schema.Faas prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code schema.Faas}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:schema.Faas)
                com.spaceuptech.clientapi.Schema.FaasOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.spaceuptech.clientapi.Schema.internal_static_schema_Faas_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.spaceuptech.clientapi.Schema.internal_static_schema_Faas_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.spaceuptech.clientapi.Schema.Faas.class, com.spaceuptech.clientapi.Schema.Faas.Builder.class);
            }

            // Construct using com.spaceuptech.clientapi.Schema.Faas.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                engine_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                func_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                args_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.spaceuptech.clientapi.Schema.internal_static_schema_Faas_descriptor;
            }

            public com.spaceuptech.clientapi.Schema.Faas getDefaultInstanceForType() {
                return com.spaceuptech.clientapi.Schema.Faas.getDefaultInstance();
            }

            public com.spaceuptech.clientapi.Schema.Faas build() {
                com.spaceuptech.clientapi.Schema.Faas result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.spaceuptech.clientapi.Schema.Faas buildPartial() {
                com.spaceuptech.clientapi.Schema.Faas result = new com.spaceuptech.clientapi.Schema.Faas(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.engine_ = engine_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.func_ = func_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.args_ = args_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.spaceuptech.clientapi.Schema.Faas) {
                    return mergeFrom((com.spaceuptech.clientapi.Schema.Faas)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.spaceuptech.clientapi.Schema.Faas other) {
                if (other == com.spaceuptech.clientapi.Schema.Faas.getDefaultInstance()) return this;
                if (other.hasEngine()) {
                    bitField0_ |= 0x00000001;
                    engine_ = other.engine_;
                    onChanged();
                }
                if (other.hasFunc()) {
                    bitField0_ |= 0x00000002;
                    func_ = other.func_;
                    onChanged();
                }
                if (other.hasArgs()) {
                    setArgs(other.getArgs());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasEngine()) {
                    return false;
                }
                if (!hasFunc()) {
                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.spaceuptech.clientapi.Schema.Faas parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.spaceuptech.clientapi.Schema.Faas) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object engine_ = "";
            /**
             * <code>required string engine = 1;</code>
             */
            public boolean hasEngine() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required string engine = 1;</code>
             */
            public java.lang.String getEngine() {
                java.lang.Object ref = engine_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        engine_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string engine = 1;</code>
             */
            public com.google.protobuf.ByteString
            getEngineBytes() {
                java.lang.Object ref = engine_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    engine_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string engine = 1;</code>
             */
            public Builder setEngine(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                engine_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string engine = 1;</code>
             */
            public Builder clearEngine() {
                bitField0_ = (bitField0_ & ~0x00000001);
                engine_ = getDefaultInstance().getEngine();
                onChanged();
                return this;
            }
            /**
             * <code>required string engine = 1;</code>
             */
            public Builder setEngineBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                engine_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object func_ = "";
            /**
             * <code>required string func = 2;</code>
             */
            public boolean hasFunc() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>required string func = 2;</code>
             */
            public java.lang.String getFunc() {
                java.lang.Object ref = func_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        func_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string func = 2;</code>
             */
            public com.google.protobuf.ByteString
            getFuncBytes() {
                java.lang.Object ref = func_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    func_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string func = 2;</code>
             */
            public Builder setFunc(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                func_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string func = 2;</code>
             */
            public Builder clearFunc() {
                bitField0_ = (bitField0_ & ~0x00000002);
                func_ = getDefaultInstance().getFunc();
                onChanged();
                return this;
            }
            /**
             * <code>required string func = 2;</code>
             */
            public Builder setFuncBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                func_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString args_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>optional bytes args = 3;</code>
             */
            public boolean hasArgs() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>optional bytes args = 3;</code>
             */
            public com.google.protobuf.ByteString getArgs() {
                return args_;
            }
            /**
             * <code>optional bytes args = 3;</code>
             */
            public Builder setArgs(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                args_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional bytes args = 3;</code>
             */
            public Builder clearArgs() {
                bitField0_ = (bitField0_ & ~0x00000004);
                args_ = getDefaultInstance().getArgs();
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:schema.Faas)
        }

        // @@protoc_insertion_point(class_scope:schema.Faas)
        private static final com.spaceuptech.clientapi.Schema.Faas DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.spaceuptech.clientapi.Schema.Faas();
        }

        public static com.spaceuptech.clientapi.Schema.Faas getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<Faas>
                PARSER = new com.google.protobuf.AbstractParser<Faas>() {
            public Faas parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Faas(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Faas> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Faas> getParserForType() {
            return PARSER;
        }

        public com.spaceuptech.clientapi.Schema.Faas getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_schema_Message_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_schema_Message_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_schema_Faas_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_schema_Faas_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\014schema.proto\022\006schema\"\210\001\n\007Message\022\"\n\004ty" +
                        "pe\030\001 \002(\0162\024.schema.Message.Type\022\014\n\004data\030\002" +
                        " \001(\014\022\032\n\004faas\030\003 \001(\0132\014.schema.Faas\"/\n\004Type" +
                        "\022\010\n\004PING\020\000\022\010\n\004PONG\020\001\022\t\n\005PROXY\020\002\022\010\n\004FAAS\020" +
                        "\003\"2\n\004Faas\022\016\n\006engine\030\001 \002(\t\022\014\n\004func\030\002 \002(\t\022" +
                        "\014\n\004args\030\003 \001(\014B#\n\031com.spaceuptech.clienta" +
                        "piB\006Schema"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_schema_Message_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_schema_Message_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_schema_Message_descriptor,
                new java.lang.String[] { "Type", "Data", "Faas", });
        internal_static_schema_Faas_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_schema_Faas_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_schema_Faas_descriptor,
                new java.lang.String[] { "Engine", "Func", "Args", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}